### ISSUE TITLE
Remove empty lines in generate CSV files

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coordination-simulation#64] opened 2019-07-30 12:25 UTC
Generated CSV files for placement etc always have blank lines in between:

```
time,node,sf

0,pop0,b

0,pop0,c

0,pop0,a
```

Very low priority, but if easy & fast to fix it would be nice to get rid of them. Else just keep issue open for now

**Comment by qarawlus** [comment] 2019-07-30 12:26
I tested this on windows and linux and was not able to reproduce it. On which platform was this recorded?

**Comment by svenuthe** [comment] 2019-07-30 12:41
smells like a line ending line feed platform issue

**Comment by qarawlus** [comment] 2019-07-30 16:00
Fixed in latest merge. As Sven said, it was indeed a Windows issue, the files generated using the windows CSV version add endings to lines in a weird order that confuses the system.

**Closed by qarawlus** 2019-07-30 16:00 UTC
Labels: bug, priority: low
