### ISSUE TITLE
[fix] Same number of flows for all Algorithms

### ISSUE THREAD

**Issue by adnan904** [RealVNF/coordination-simulation#129] opened 2020-02-25 16:50 UTC
When running the RL and Non-RL algorithms with the same input file as well as the seeds, the expected behaviour is that the simulator produces the same number of flows. Currently this is not happening.

This issue is to test the different Algorithms for the same inputs and seeds and identify why the results don't show the same number of flows.

**Comment by adnan904** [comment] 2020-02-25 16:56
So far what I've identified is:
- Running the same algorithm(DDPG, SP, RS, LB) 2+ times produces the same number of flows for same input files and seed
- For same input files and seed, different algorithms produce different number of flows
- The simulator is getting the seed passed on via the CLI
- `run_duration` has an impact on the number of flows produces. E.g: `SP` with run_duration = 100 and iterations = 200 & run_duration = 200 and iterations = 100, produces different number of flows.

**Comment by qarawlus** [comment] 2020-02-25 21:21
I have tried numerous debugging methods to try and get to the bottom of the issue, below is a summary from the first 5 iterations of both RS and LB algorithms:
```
LB 
Switch to state 2 in 
i: 7
Iteration - #flows
1- 9
2- 15
3- 26
4- 35
5- 39

RS
Switch to state 2 in 
i: 44
Iteration and #flows
1- 17
2- 31
3- 43
4- 51
5- 65

```

I have went through the simulator code, it is seeded correctly. To make sure, I added another seed plant code in the simulator params file where the state switch is conducted, but with no result. 

I believe that the problem is not with the simulator not getting the seed, it seems to be something related to the context in which the simulator is called as well since seeding is indeed working for the same algorithm. Will need to further check on this.

**Comment by stefanbschneider** [comment] 2020-02-26 08:08
Basically, the seed determines the sequence of random numbers or decisions made by the random module.Same seed leads to the same sequence of random numbers.Possible reasons why we still get different flows with same sim seed but different algos:* we seed again in the algorithm. Not sure if this will overwrite the sim seed. AFAIK, seeding should only be done once at the beginning of the program flow.* we call the random module different number of times for the different algos. Eg, while the sequence of rand numbers may be determined by the seed, eg, 5 7 9 8, if we have an additional random call in one algo (or caused by it), we're at different positions in the rand sequence, leading to different flow arrivalsThese issues may not be avoidable. In that case, we should simply clearly state it in the readme and move on. If we average over enough repetitions, it should be fine for the eval.Let's not lose too much time on this. -------- Original Message --------Subject: Re: [RealVNF/coordination-simulation] [fix] Same number of flows for all Algorithms (#129)From: Haydar Qarawlus To: RealVNF/coordination-simulation CC: Subscribed I have tried numerous debugging methods to try and get to the bottom of the issue, below is a summary from the first 5 iterations of both RS and LB algorithms:
LB 
Switch to state 2 in 
i: 7
Iteration - #flows
1- 9
2- 15
3- 26
4- 35
5- 39

RS
Switch to state 2 in 
i: 44
Iteration and #flows
1- 17
2- 31
3- 43
4- 51
5- 65


I have went through the simulator code, it is seeded correctly. To make sure, I added another seed plant code in the simulator params file where the state switch is conducted, but with no result.
I believe that the problem is not with the simulator not getting the seed, it seems to be something related to the context in which the simulator is called as well since seeding is indeed working for the same algorithm. Will need to further check on this.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/RealVNF/coordination-simulation/issues/129?email_source=notifications\u0026email_token=AGYHEQXOR3NFJYJFZSRCLQ3REWDU7A5CNFSM4K3OCKD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5RPLY#issuecomment-591075247",
"url": "https://github.com/RealVNF/coordination-simulation/issues/129?email_source=notifications\u0026email_token=AGYHEQXOR3NFJYJFZSRCLQ3REWDU7A5CNFSM4K3OCKD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEM5RPLY#issuecomment-591075247",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by qarawlus** [comment] 2020-02-29 16:21
I have experimented with this and used `RandomState` as the simulator's random generator, but I was not able to produce same number of flows in different algorithms. It appears that `RandomState` is still linked to the original seed and how random generators are used. I reverted the changes I made and did not push any commits because I was worried that it might affect our current result. 

I suggest that we close this, and just go with using the mean of several runs.

**Comment by stefanbschneider** [comment] 2020-03-02 07:11
I agree. 

Could you still add a comment in the readme and/or description of the `-sim_seed` CLI arg, clarifying that this can be used for reproducable/deterministic simulator behavior when using the same algorithm, but not across different algorithms because they may use `random` internally. You can link to this issue for details.

**Closed by stefanbschneider** 2020-03-02 07:11 UTC
Labels: bug
